import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import {StationsState, SearchOptions} from './types'
import {getStationsThunk} from './thunks'
const initialState: StationsState = {
  searchOptions: []
};


export const stationsSlice = createSlice({
  name: 'stations',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder.addCase(getStationsThunk.fulfilled, (state, action: PayloadAction<SearchOptions[]>) => {
      state.searchOptions = action.payload
    })
  },
});



export default stationsSlice.reducer;
